ALTER TABLE data RENAME TO temp;

CREATE TABLE data (
id                INTEGER PRIMARY KEY AUTOINCREMENT,
ind               INTEGER NULL,
file_name         INTEGER NULL,
num_recs          TEXT NULL,
file_hours        INTEGER NULL,
child_id          REAL NULL,
child_age         TEXT NULL,
child_gender      INTEGER NULL,
awc               TEXT NULL,
turn_count        INTEGER NULL,
child_voc_count   INTEGER NULL,
chn               REAL NULL,
child_voc_dur     REAL NULL,
fan_word_count    INTEGER NULL,
fan               REAL NULL,
man_word_count    REAL NULL,
man               REAL NULL,
cxn               REAL NULL,
oln               REAL NULL,
tvn               REAL NULL,
non               REAL NULL,
sil               REAL NULL,
emlu              TEXT NULL,
ava_da            INTEGER NULL,
rec_index         INTEGER NULL,
el_time           INTEGER NULL,
clock_time_tzadj  TEXT NULL,
audio_dur         REAL NULL,
adult_count       INTEGER NULL,
child_count       INTEGER NULL,
adult_child_ratio REAL NULL,
naptime           TEXT NULL,
wav_begin         REAL NULL,
wav_end           REAL NULL
);

INSERT INTO data (
ind,
file_name,
num_recs,
file_hours,
child_id,
child_age,
child_gender,
awc,
turn_count,
child_voc_count,
chn,
child_voc_dur,
fan_word_count,
fan,
man_word_count,
man,
cxn,
oln,
tvn,
non,
sil,
emlu,
ava_da,
rec_index,
el_time,
clock_time_tzadj,
audio_dur,
adult_count,
child_count,
adult_child_ratio,
naptime,
wav_begin,
wav_end
)
SELECT
col0,
col1,
col2,
col3,
col4,
col5,
col6,
col7,
col8,
col9,
col10,
col11,
col12,
col13,
col14,
col15,
col16,
col17,
col18,
col19,
col20,
col21,
col22,
col23,
col24,
col25,
col26,
col27,
col28,
col29,
col30,
col31,
col32
 FROM temp;

DROP TABLE temp;

UPDATE DATA SET file_name = replace(file_name, '.its', '');
